name: myapp
description: A exported flutter project from FUNCTION12

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  image_picker: ^1.0.2
  fluttertoast: ^8.2.4
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  razorpay_flutter: ^1.3.7
  circular_countdown_timer: ^0.2.3
  device_preview: ^1.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  otp_text_field: ^1.1.3
  flutter_easyloading: ^3.0.3
  http: ^1.1.0
  get: ^4.6.5
  email_validator: ^2.0.1
  provider: ^6.1.1
  readmore: ^3.0.0
  flutter_image_slideshow: ^0.1.6
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  animated_text_kit: ^4.2.2
  internet_connection_checker: ^1.0.0+1
  # connectivity_plus: ^6.0.3
  jiffy: ^6.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.0
  share_plus: ^9.0.0
  delete_un_used_assets: ^1.0.1
  flutter_email_sender: ^6.0.3
  modal_progress_hud_nsn: ^0.5.1
  rename_app: ^1.3.2
  shimmer: ^3.0.0

  dio: ^5.4.3+1
  flutter_image_compress: ^2.3.0
  flutter_svg: ^2.0.10+1
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  
  assets:
    - assets/page-1/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
