// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcnBi55pQSgrxrV38sr5OmyUoY9sDTkmM',
    appId: '1:797019013724:web:a1afc86b48cf3a72309c99',
    messagingSenderId: '797019013724',
    projectId: 'sort-my-college-a47a7',
    authDomain: 'sort-my-college-a47a7.firebaseapp.com',
    storageBucket: 'sort-my-college-a47a7.firebasestorage.app',
    measurementId: 'G-EMXVEVHFYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZN49HJUSkOi2NmLIb09_ja8wk6mXBXmM',
    appId: '1:797019013724:android:19302303ab5e2c4b309c99',
    messagingSenderId: '797019013724',
    projectId: 'sort-my-college-a47a7',
    storageBucket: 'sort-my-college-a47a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUfsW76ehCdjz0ye8a0TAC6u-XYQuZl6g',
    appId: '1:797019013724:ios:2b2b863140bee858309c99',
    messagingSenderId: '797019013724',
    projectId: 'sort-my-college-a47a7',
    storageBucket: 'sort-my-college-a47a7.firebasestorage.app',
    iosBundleId: 'com.sortmycollege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUfsW76ehCdjz0ye8a0TAC6u-XYQuZl6g',
    appId: '1:797019013724:ios:2b2b863140bee858309c99',
    messagingSenderId: '797019013724',
    projectId: 'sort-my-college-a47a7',
    storageBucket: 'sort-my-college-a47a7.firebasestorage.app',
    iosBundleId: 'com.sortmycollege',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcnBi55pQSgrxrV38sr5OmyUoY9sDTkmM',
    appId: '1:797019013724:web:bae988a3f3750afa309c99',
    messagingSenderId: '797019013724',
    projectId: 'sort-my-college-a47a7',
    authDomain: 'sort-my-college-a47a7.firebaseapp.com',
    storageBucket: 'sort-my-college-a47a7.firebasestorage.app',
    measurementId: 'G-E0PWBVX15K',
  );
}
